application/views.py
from crypt import methods
import io
import gridfs
import urllib.parse
from PIL import Image
import re
import os
from bson.objectid import ObjectId
import datetime
import mistune
from .database import mongo
from flask.wrappers import Response
from flask import request
from .models import post_job, get_active_jobs, save_email, id_generator, get_file_extension, find_and_delete_file, allowed_file, increment_value
from flask import render_template, Blueprint, redirect, url_for, session
from .forms import NewJobSubmission, NewsletterSubscribe, UploadPicture
from .decorators import login_required
from .emails import send_email
from flask_simplemde import SimpleMDE
from werkzeug.utils import secure_filename

bp = Blueprint('main', __name__)

simplemde = SimpleMDE()


@bp.route('/', methods=["GET", "POST"])
def home():

    recent_jobs = get_active_jobs()[:5]

    categories_list = [
        get_active_jobs(category="development")[:5],
        get_active_jobs(category="design")[:5],
        get_active_jobs(category="marketing")[:5],
        get_active_jobs(category="product management")[:5],
        get_active_jobs(category="business development")[:5],
        get_active_jobs(category="other")[:5]
    ]

    subscribe_form = NewsletterSubscribe()

    if subscribe_form.validate_on_submit():
        save_email(subscribe_form.MERGE0.data)
        return redirect(url_for('main.home'))

    return render_template('home.html',
                           subscribe_form=subscribe_form,
                           recent_jobs=recent_jobs,
                           categories_list=categories_list)


@bp.post('/newJob')
def newJob():
    form = NewJobSubmission()
    company = form.company.data
    job_title = form.title.data

    if form.validate_on_submit():

        post_job(title=form.title.data,
                 company=form.company.data,
                 category=form.category.data,
                 location=form.location.data,
                 description=form.description.data,
                 link=form.link.data,
                 email=form.email.data,
                 status="active",
                 visa_sponsor=form.visa_sponsor.data)
        # Notification sent to the person who submitted the job.
        send_email(subject='Your submission | Fuzzboard',
                   to=form.email.data,
                   template='mail/new_job',
                   job_title=job_title,
                   company=company)
        # Notification sent to myself.
        send_email(subject='New submission at Fuzzboard',
                   to=os.environ.get('MAIL_DEFAULT_RECEIVER'),
                   template='mail/submission_notification',
                   job_title=job_title,
                   company=company)

        return job_submitted()


@bp.get('/new/ukraine')
def new():
    """     form = NewJobSubmission()

    return render_template('new.html', form=form) """
    return redirect(url_for('main.new_ukraine'))


@bp.get('/new_job_form')
def new_job_form():
    form = NewJobSubmission()

    return render_template('fragments/new_job_form.html', form=form)


@bp.get('/get_jobs/<category>')
def htmx_get_jobs(category):
    jobs = get_active_jobs(category=category)
    subscribe_form = NewsletterSubscribe()

    return render_template('fragments/get_jobs.html', jobs=jobs, category=category, subscribe_form=subscribe_form)


@bp.get('/get_jobs/visa/<category>')
def htmx_get_jobs_visa(category):
    jobs = get_active_jobs(category=category, visa_sponsor=True)
    subscribe_form = NewsletterSubscribe()

    return render_template('fragments/get_jobs_visa.html', jobs=jobs, category=category, subscribe_form=subscribe_form)


@bp.post('/<id>/bookmark')
def bookmark(id):
    # Start of Session.
    if 'saved_jobs' not in session:
        session['saved_jobs'] = []

    # id = ObjectId(id)

    if id in session['saved_jobs']:
        return Response(status=400)

    session['saved_jobs'].append(id)
    session.modified = True

    return Response(status=200)


@bp.post('/<id>/remove_bookmark')
def remove_bookmark(id):

    session['saved_jobs'].remove(id)
    session.modified = True

    return Response(status=200)


@bp.get('/<category>')
def category(category):
    jobs = get_active_jobs(category=category)

    if len(jobs) == 0:
        return redirect(url_for('main.home'))

    return render_template('category_page.html', category=category, jobs=jobs)


# Ukraine CASAFARI page.
@bp.get('/visa')
def visa():

    return redirect(url_for('main.visa_ukraine'))


@bp.get('/ukraine')
def visa_ukraine():
    return redirect(url_for('main.home'))


@bp.get('/company/<company>')
def company(company):
    jobs = get_active_jobs(company=company)

    if len(jobs) == 0:
        return redirect(url_for('main.home'))

    return render_template('company_page.html', company=company, jobs=jobs)


@bp.get('/location/<location>')
def location(location):
    jobs = get_active_jobs(location=location)

    if len(jobs) == 0:
        return redirect(url_for('main.home'))

    return render_template('location_page.html', location=location, jobs=jobs)


@bp.route('/jobs/<slug>', methods=["GET", "POST"])
def jobs(slug):
    # TODO: Replace get active jobs with a new get job function.
    # TODO: I wonder if there's a better way to handle "days ago"
    jobs = get_active_jobs(slug=slug)

    today = datetime.datetime.now().replace(microsecond=0)

    for job in jobs:
        job["description"] = mistune.html(job["description"])
        job["timestamp"] = job["timestamp"].replace(tzinfo=None)

        # Removing HTML tags and characters from job description.
        CLEANR = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
        clean_description = re.sub(CLEANR, '', job["description"])[:1000]

        days_ago = (today - job["timestamp"])

        # if the characters are less than 8, that means
        # they don't have "days" yet.
        is_less_than_one_day = len(str(days_ago)) <= 8

        days_ago = str(days_ago).split(",")[0] + " " + "ago"

        if is_less_than_one_day:
            days_ago = "Today"

    if len(jobs) == 0:
        return redirect(url_for('main.home'))

    return render_template('job_page.html', jobs=jobs, slug=slug, days_ago=days_ago, clean_description=clean_description)


@bp.post('/<id>/increment')
def increment(id):
    increment_value(id=id, key='stats.num_of_applies')

    return Response(status=200)


@ bp.get('/job_submitted')
def job_submitted():

    return render_template('fragments/job_submitted.html')


@ bp.route('/settings', methods=["GET", "POST"])
@ login_required
def settings():
    fs = gridfs.GridFS(mongo.db)

    username = session.get("username")
    user = mongo.db.users.find_one_or_404({'email': username})

    form = UploadPicture()
    profile_image = form.file.data

    # if the form validates on submit and if the
    # file extension is allowed. Should probably check if the file is allowed
    # before letting the user upload a file.
    if form.validate_on_submit() and allowed_file(profile_image.filename):
        # If the upload files, the photo will be deleted.
        # Delete old file after submission.
        if user["profile_image_name"] != "default.png":
            find_and_delete_file(user["profile_image_name"])

        # I'm replacing the file name uploaded by the user
        # by a random string + the original file extension.
        # TODO: Prefix the file name with something that binds it to the user.
        filename = secure_filename(
            id_generator() + get_file_extension(profile_image.filename))

        outfile = io.BytesIO()

        with Image.open(profile_image) as im:
            (left, upper, right, lower) = (0, 0, 300, 300)
            croppedImage = im.crop((left, upper, right, lower))
            width, height = im.size

        # If the photo uploaded is already a square, don't crop it.
            if width == height:
                im.save(outfile, "JPEG")
            else:
                croppedImage.save(outfile, "JPEG")

        # Saving file on MongoDB.
        fs.put(outfile.getvalue(), filename=filename)

        mongo.db.users.update_one(
            {'_id': user['_id']}, {'$set': {'profile_image_name': filename}})
        return redirect(url_for('main.settings'))

    return render_template("settings.html", username=username, user=user, form=form)


@ bp.route('/file/<filename>')
def file(filename):
    return mongo.send_file(filename)


@ bp.get('/profile/<username>')
@ login_required
def profile(username):
    user = mongo.db.users.find_one_or_404({'name': username})

    return render_template("profile.html", username=username, user=user)

# Mission Ukraine


@ bp.get('/new')
def new_ukraine():

    return render_template('ukraine/new_ukraine.html')


@bp.get('/cities')
def get_city():
    if request.args.get('location') == 'portugal':
        return render_template('fragments/cities/portugal.html')

    else:
        return print("nothing is being returned")


@bp.post('/newJobUkraine')
def newJobUkraine():
    company = request.form['company']
    job_title = request.form['title']

    post_job(title=request.form['title'],
             company=request.form['company'],
             category=request.form['category'],
             location=request.form['city'],
             description=request.form['description'],
             link=request.form['link'],
             email=request.form['email'],
             status="active",
             visa_sponsor=bool(request.form['visa_sponsor']))
    # Notification sent to the person who submitted the job.
    send_email(subject='Your submission | Fuzzboard',
               to=request.form['email'],
               template='mail/new_job',
               job_title=job_title,
               company=company)
    # Notification sent to myself.
    send_email(subject='New submission at Fuzzboard',
               to=os.environ.get('MAIL_DEFAULT_RECEIVER'),

application/templates/fragments/get_jobs.html
<script src="{{url_for('static', filename='js/htmx.min.js')}}"></script>
<nav class="job-categories">
    <ul class="filter-categories">
        <li {% if category == "all" %}class="active"{%endif%}>All</li>
        <li {% if category == "development" %}class="active"{%endif%} hx-get="/get_jobs/development" hx-trigger="click" hx-target="#replaceMe">Development</li>
        <li {% if category == "design" %}class="active"{%endif%} hx-get="/get_jobs/design" hx-trigger="click" hx-target="#replaceMe">Design</li>
        <li {% if category == "marketing" %}class="active"{%endif%} hx-get="/get_jobs/marketing" hx-trigger="click" hx-target="#replaceMe">Marketing</li>
        <li {% if category == "product management" %}class="active"{%endif%} hx-get="/get_jobs/product management" hx-trigger="click" hx-target="#replaceMe">Product Management</li>
        <li {% if category == "business development" %}class="active"{%endif%} hx-get="/get_jobs/business development" hx-trigger="click" hx-target="#replaceMe">Business Development</li>
        <li {% if category == "other" %}class="active"{%endif%} hx-get="/get_jobs/other" hx-trigger="click" hx-target="#replaceMe">Others</li>
    </ul>
</nav>

<div class="jobs-container">

        {%- for job in jobs | batch(5) %}
            {%- for entry in job %}
                
                    <div class="card-container testing">

                        <div class="job-card">
                            <a href="{{ url_for('main.jobs', slug=entry.slug) }}">
                                <h3 class="card-header">{{ entry.title }}</h3>
                            </a>
                        
                            <a class="company-hyperlink " href="{{ url_for('main.company', company=entry.company) }}">
                                <span>{{ entry.company }}</span>
                            </a>
                        </div>

                        <div class="job-card-location">
                            <svg class="mr-1/2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="#9E9E9E" d="M12 13.5C11.2583 13.5 10.5333 13.2801 9.91661 12.868C9.29993 12.456 8.81928 11.8703 8.53545 11.1851C8.25162 10.4998 8.17736 9.74584 8.32206 9.01841C8.46675 8.29098 8.8239 7.6228 9.34835 7.09835C9.8728 6.5739 10.541 6.21675 11.2684 6.07206C11.9958 5.92736 12.7498 6.00162 13.4351 6.28545C14.1203 6.56928 14.706 7.04993 15.118 7.66661C15.5301 8.2833 15.75 9.00832 15.75 9.75C15.7489 10.7442 15.3534 11.6974 14.6504 12.4004C13.9474 13.1034 12.9942 13.4989 12 13.5ZM12 7.5C11.555 7.5 11.12 7.63196 10.75 7.8792C10.38 8.12643 10.0916 8.47783 9.92127 8.88896C9.75098 9.3001 9.70642 9.7525 9.79323 10.189C9.88005 10.6254 10.0943 11.0263 10.409 11.341C10.7237 11.6557 11.1246 11.87 11.561 11.9568C11.9975 12.0436 12.4499 11.999 12.861 11.8287C13.2722 11.6584 13.6236 11.37 13.8708 11C14.118 10.63 14.25 10.195 14.25 9.75C14.2493 9.15347 14.0121 8.58155 13.5903 8.15974C13.1685 7.73792 12.5965 7.50066 12 7.5Z"></path><path fill="#9E9E9E" d="M12 22.5L5.67338 15.0385C5.63746 14.9957 5.41223 14.6999 5.41223 14.6999C4.33141 13.2763 3.74748 11.5374 3.75001 9.75C3.75001 7.56196 4.6192 5.46354 6.16638 3.91637C7.71355 2.36919 9.81197 1.5 12 1.5C14.188 1.5 16.2865 2.36919 17.8336 3.91637C19.3808 5.46354 20.25 7.56196 20.25 9.75C20.2527 11.5367 19.6692 13.2749 18.5889 14.698L18.5878 14.6999C18.5878 14.6999 18.3628 14.9956 18.3293 15.0354L12 22.5ZM6.60938 13.7963C6.61013 13.7968 6.78443 14.0274 6.82433 14.077L12 20.1809L17.1825 14.0684C17.2154 14.027 17.3912 13.7948 17.3916 13.7942C18.2746 12.631 18.7517 11.2103 18.75 9.75C18.75 7.95979 18.0388 6.2429 16.773 4.97703C15.5071 3.71116 13.7902 3 12 3C10.2098 3 8.49291 3.71116 7.22704 4.97703C5.96117 6.2429 5.25001 7.95979 5.25001 9.75C5.24835 11.2111 5.72587 12.6325 6.60938 13.7963Z"></path></svg>
                            <a href="{{ url_for('main.location', location=entry.location) }}">
                                <span>{{ entry.location }}</span>
                            </a>
                        </div>
                        <div class="tooltip" id="saveJob">
                            <div id="response-div"></div>
                            <span class="tooltiptext">Save job</span>
                            
                                 <button class="save-button" onclick="setTimeout(function() { window.location='{{ url_for('main.savedJobs') }}' }, 100)" hx-target="#response-div" hx-post="/{{ job._id }}/bookmark" method="POST">
                                <svg class="save-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M 6.0097656 2 C 4.9143111 2 4.0097656 2.9025988 4.0097656 3.9980469 L 4 22 L 12 19 L 20 22 L 20 20.556641 L 20 4 C 20 2.9069372 19.093063 2 18 2 L 6.0097656 2 z M 6.0097656 4 L 18 4 L 18 19.113281 L 12 16.863281 L 6.0019531 19.113281 L 6.0097656 4 z"></path></svg>
                                </button>
                        </div>
                    </div>
                
                
                {%- endfor %}
        
                <div class="email-subscribe">
                    <span>Get the latest jobs in your inbox every week.</span>
                    <div>
                    <form method="POST" autocomplete="off" action="https://hey.us6.list-manage.com/subscribe/post">
                    {{ subscribe_form.hidden_tag() }}
                    <input type="hidden" name="u" value="836c6f357c7afce413d17dce1">
                    <input type="hidden" name="id" value="d05c7f7f10">
                    {{ subscribe_form.MERGE0(placeholder="mail@example.com") }}
                    {{ subscribe_form.submit }}
                    </form>
                    </div>
                </div>
        {%- endfor %}
    </div>

application/templates/fragments/get_jobs_visa.html
<script src="{{url_for('static', filename='js/htmx.min.js')}}"></script>
<nav class="job-categories">
    <ul class="filter-categories">
        <li {% if category == "all" %}class="active"{%endif%}>All</li>
        <li {% if category == "development" %}class="active"{%endif%} hx-get="/get_jobs/visa/development" hx-trigger="click" hx-target="#replaceMe">Development</li>
        <li {% if category == "design" %}class="active"{%endif%} hx-get="/get_jobs/visa/design" hx-trigger="click" hx-target="#replaceMe">Design</li>
        <li {% if category == "marketing" %}class="active"{%endif%} hx-get="/get_jobs/visa/marketing" hx-trigger="click" hx-target="#replaceMe">Marketing</li>
        <li {% if category == "product management" %}class="active"{%endif%} hx-get="/get_jobs/visa/product management" hx-trigger="click" hx-target="#replaceMe">Product Management</li>
        <li {% if category == "business development" %}class="active"{%endif%} hx-get="/get_jobs/visa/business development" hx-trigger="click" hx-target="#replaceMe">Business Development</li>
        <li {% if category == "other" %}class="active"{%endif%} hx-get="/get_jobs/visa/other" hx-trigger="click" hx-target="#replaceMe">Others</li>
    </ul>
</nav>

<div class="jobs-container">

        {%- for job in jobs | batch(5) %}
            {%- for entry in job %}
                
                    <div class="card-container testing">

                        <div class="job-card">
                            <a href="{{ url_for('main.jobs', slug=entry.slug) }}">
                                <h3 class="card-header">{{ entry.title }}</h3>
                            </a>
                        
                            <a class="company-hyperlink " href="{{ url_for('main.company', company=entry.company) }}">
                                <span>{{ entry.company }}</span>
                            </a>
                        </div>

                        <div class="job-card-location">
                            <svg class="mr-1/2" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24"><path fill="#9E9E9E" d="M12 13.5C11.2583 13.5 10.5333 13.2801 9.91661 12.868C9.29993 12.456 8.81928 11.8703 8.53545 11.1851C8.25162 10.4998 8.17736 9.74584 8.32206 9.01841C8.46675 8.29098 8.8239 7.6228 9.34835 7.09835C9.8728 6.5739 10.541 6.21675 11.2684 6.07206C11.9958 5.92736 12.7498 6.00162 13.4351 6.28545C14.1203 6.56928 14.706 7.04993 15.118 7.66661C15.5301 8.2833 15.75 9.00832 15.75 9.75C15.7489 10.7442 15.3534 11.6974 14.6504 12.4004C13.9474 13.1034 12.9942 13.4989 12 13.5ZM12 7.5C11.555 7.5 11.12 7.63196 10.75 7.8792C10.38 8.12643 10.0916 8.47783 9.92127 8.88896C9.75098 9.3001 9.70642 9.7525 9.79323 10.189C9.88005 10.6254 10.0943 11.0263 10.409 11.341C10.7237 11.6557 11.1246 11.87 11.561 11.9568C11.9975 12.0436 12.4499 11.999 12.861 11.8287C13.2722 11.6584 13.6236 11.37 13.8708 11C14.118 10.63 14.25 10.195 14.25 9.75C14.2493 9.15347 14.0121 8.58155 13.5903 8.15974C13.1685 7.73792 12.5965 7.50066 12 7.5Z"></path><path fill="#9E9E9E" d="M12 22.5L5.67338 15.0385C5.63746 14.9957 5.41223 14.6999 5.41223 14.6999C4.33141 13.2763 3.74748 11.5374 3.75001 9.75C3.75001 7.56196 4.6192 5.46354 6.16638 3.91637C7.71355 2.36919 9.81197 1.5 12 1.5C14.188 1.5 16.2865 2.36919 17.8336 3.91637C19.3808 5.46354 20.25 7.56196 20.25 9.75C20.2527 11.5367 19.6692 13.2749 18.5889 14.698L18.5878 14.6999C18.5878 14.6999 18.3628 14.9956 18.3293 15.0354L12 22.5ZM6.60938 13.7963C6.61013 13.7968 6.78443 14.0274 6.82433 14.077L12 20.1809L17.1825 14.0684C17.2154 14.027 17.3912 13.7948 17.3916 13.7942C18.2746 12.631 18.7517 11.2103 18.75 9.75C18.75 7.95979 18.0388 6.2429 16.773 4.97703C15.5071 3.71116 13.7902 3 12 3C10.2098 3 8.49291 3.71116 7.22704 4.97703C5.96117 6.2429 5.25001 7.95979 5.25001 9.75C5.24835 11.2111 5.72587 12.6325 6.60938 13.7963Z"></path></svg>
                            <a href="{{ url_for('main.location', location=entry.location) }}">
                                <span>{{ entry.location }}</span>
                            </a>
                        </div>
                        <div class="tooltip" id="saveJob">
                            <div id="response-div"></div>
                            <span class="tooltiptext">Save job</span>
                            
                                 <button class="save-button" onclick="setTimeout(function() { window.location='{{ url_for('main.savedJobs') }}' }, 100)" hx-target="#response-div" hx-post="/{{ job._id }}/bookmark" method="POST">
                                <svg class="save-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M 6.0097656 2 C 4.9143111 2 4.0097656 2.9025988 4.0097656 3.9980469 L 4 22 L 12 19 L 20 22 L 20 20.556641 L 20 4 C 20 2.9069372 19.093063 2 18 2 L 6.0097656 2 z M 6.0097656 4 L 18 4 L 18 19.113281 L 12 16.863281 L 6.0019531 19.113281 L 6.0097656 4 z"></path></svg>
                                </button>
                        </div>
                    </div>
                
                
                {%- endfor %}
        
                <div class="email-subscribe">
                    <span>Get new visa-sponsored jobs in your inbox once a week.</span>
                    <div>
                    <form method="POST" autocomplete="off" action="https://outono.us6.list-manage.com/subscribe/post">
                    {{ subscribe_form.hidden_tag() }}
                    <input type="hidden" name="u" value="836c6f357c7afce413d17dce1">
                    <input type="hidden" name="id" value="c7c80facb3">
                    {{ subscribe_form.MERGE0(placeholder="mail@example.com") }}
                    {{ subscribe_form.submit }}
                    </form>
                    </div>
                </div>
        {%- endfor %}
    </div>

application/templates/fragments/job_submitted.html
<div id="replaceMeToo">
    <!-- <div hx-get="/new_job_form" hx-trigger="click" class="success-message" hx-target="#replaceMeToo" hx-swap="outerHTML"> -->
        <div class="success-message">
        <div>
            <h1>Hurray! Your job was submitted.</h1>
            <span class="secondary-text">Give us some time to review and approve your post. It usually takes less than 24 hours.</span>
        </div><br>
        <a class="a_underline" href="{{ url_for('main.new') }}">Add a new job.</a>
    </div>
</div>

application/templates/fragments/new_job_form.html
<div class="new-job-form">
    {{mde.js}}
    
    <form class="new-job-form" hx-post="/newJob" method="POST" hx-swap="innerHTML" hx-target="#replaceMe">
        {{ form.hidden_tag() }}

        <div class="new-job-form-left">
            <div class="flex-col">
                {{ form.title.label }}
                {{ form.title(placeholder="Senior fullstack developer") }}
            </div>
        
            <div class="flex-col">
            {{ form.company.label }}
            {{ form.company(placeholder="Upframe") }}
            </div>

            <div class="flex-col">
                {{ form.category.label }}
                {{ form.category(placeholder="Upframe") }}
            </div>

            <div class="flex-col">
                {{ form.location.label }}
                {{ form.location(placeholder="Lisbon") }}
            </div>

            <div class="flex-col">
                {{ form.link.label }}
                <small>Please submit a URL. Other formats are not accepted.</small>
                {{ form.link(placeholder="https://angel.co/company/upframe/jobs/1159754-fullstack-developer-co-founder", autocomplete="off") }}
            </div>

            <div class="flex-col">
                {{ form.email.label }}
                {{ form.email(placeholder="malik@outono.org") }}
            </div>

            <div class="flex-col">
                {{ form.submit(class="button-main") }}
            </div>
        
        </div>

        <div class="recipient flex-col">
            {{ form.description.label }}
            {{ form.description }}
            {{ simplemde.load }}
        </div>

    </form>

 </div>